### ISSUE TITLE
Empty Negotiation Response from Service/SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by spongessuck** [Azure/azure-signalr#1000]
I have a standard-tier SignalR service in Default mode which has been working, but this morning when I try to connect I get the following back from the /negotiate request forwarded by my app:

- Request (app):
    - POST https://localhost:44368/chat/negotiate?...&negotiateVersion=1
    - Response:
        200
        Body: {"negotiateVersion":0,"url":"https://....service.signalr.net/client/?hub=chathub\u0026asrs.op=%2Fchat...\u0026negotiateVersion=1\u0026asrs_request_id=ftgdb1cBAAA%3D","accessToken":"...","availableTransports":[]}

- Request (service):
    - POST https://....service.signalr.net/client/negotiate?hub=chathub&asrs.op=%2Fchat&...&negotiateVersion=1&asrs_request_id=ftgdb1cBAAA%3D
    - Response:
        200
        Body:

The following error comes back when I call HubConnection.start() in the JavaScript client:

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at HttpConnection.<anonymous> (signalr.min.js:16)
    at step (signalr.min.js:16)
    at Object.next (signalr.min.js:16)
    at fulfilled (signalr.min.js:16)

**Comment by jsheetzati** [comment]
We also started experiencing this issue with all our Azure SignalR Instances this morning. We logged a Sev-A Ticket with Azure support

**Comment by panmanphil** [comment]
We also started experiencing this with a c# based client that has been in production since last December. All systems, even running local, have started to fail which leads me to think that either something changed with the signalr service itself, or something changed in the token validation or generation that is making the negotiation fail. We get a token using the ADAL library based on the client if the app service hosting the the hub. I've verified the token exists, and this exact code is used throughout our systems for rest calls and works everywhere else. 

Please **any suggestions would be greatly appreciated**. We've also started a ticket, but it is through a vendor and takes forever to escalate.

**Comment by PaitoAnderson** [comment]
I'm having this issue as well with Azure SignalR standard tier it started this morning around 4am.

I did notice that specifying the transport type manually skipping the negotiation does seem to fix it, but I'm sure this is a terrible solution, not recommending it.

```ts
.withUrl("/chathub", {
  skipNegotiation: true,
  transport: signalR.HttpTransportType.WebSockets
})
```

**Comment by spongessuck** [comment]
@PaitoAnderson doesn't seem so bad. Thanks for the info; glad we haven't gone to production with this yet.

![image](https://user-images.githubusercontent.com/6370382/91352557-001b2880-e7b8-11ea-8785-5afba18d3ccf.png)

**Comment by jsheetzati** [comment]
Interesting that the documentation clearly states that `skipNegotiation: true` isn't supported for Azure SignalR... so that is confusing

**Comment by spongessuck** [comment]
Yeah, just noticed that. Could it be that clients are just connecting to the app itself and not the service in that case?

**Comment by jsheetzati** [comment]
Yea, when running locally, my socket is connected to localhost instead of Azure SignalR now

**Comment by panmanphil** [comment]
The way we are setup, the `Hub<IMessageHub>` does the negotiation based on the credentials passed in, convenient because this app supports openid connect, cookies and jwt for various clients. That negotiation call returns the url of the signalr server in azure along with an access token for that service and hub name. Then the client calls the azure service to negotiate, it returns a new token and the list of transports allowed. To send messages, the messages are coming from azure regardless of running local or in azure as I understand it.

I duplicated all these calls with postman. I have two different hubs in the same instance of azure signalr. One works, and returns the token and transports. The other returns 200 OK, and no data whatsoever. Hoping a call from MS signalr team is coming soon

**Comment by jsheetzati** [comment]
This is what we received so far via our support ticket. Seems like there was a new release of Azure SignalR to US-East that broke all of us.

![image](https://user-images.githubusercontent.com/15350893/91361973-095bc380-e7bf-11ea-8c1a-cf732e8f43f4.png)

**Comment by mstephens-adig** [comment]
Confirmed this also appears to be broke on new signalR instances in the west coast as well.

**Comment by spongessuck** [comment]
I was having the same issue with a new service I spun up on Monday. :shrug:

I'm just glad it doesn't seem like an issue with the SDK. I was going crazy
trying to figure out what I was doing wrong.

**Comment by vicancy** [comment]
We've identified the root cause and are hot fixing all the influenced instances. It might take ~30mins to have all the influnced instances fixed. An RCA will be provided shortly after.

**Comment by panmanphil** [comment]
This is working for me now, thanks!

**Comment by terencefan** [comment]
## RCA

### Impact:

- **Cannot create client connection (negotiation failed)**
	- Only if the customer's app server used AAD to authorize their requests.
- For resources **created recently** (resources created within the mentioned range will be impacted)
	- WestUS2
		- From 8/21 08:06 To 08/27 03:01 (UTC)
	- EastUS
		- From 8/24 07:29 To 08/27 03:01 (UTC)
	- Southeast Asia, Canada East, West Europe, Central US, UK South, South Central US
		- From 8/25 07:20 To 08/27 03:01 (UTC)
	- Australia East, North Europe, Japan East, East US 2, West US, Brazil South, France Central, Korea  Central
		- From 8/26 08:00 To 08/27 03:01 (UTC)
- For **existing** resources (all resources will be impacted within the time range)
	- WestUS2
		- From 8/24 07:12 To 8/27 03:25 (UTC) 
	- EastUS
		- From 8/26 08:01 To 8/27 03:30 (UTC)

### Root Cause
We deployed a new feature to encourage our customers to use AAD Token to access our service instead of using AccessKey. However, if our customer **had already used AAD Token to authenticate requests to their server**, our SignalR SDK will forward all the claims in that token to the ASRS, including the Issuer. In this scenario, our ASRS will falsely enter a different authorization process and decline the negotiation request **with status code 200 and an empty response body**.
### Mitigation
We rollbacked all the resources in WestUS2 / EastUS and newly created resources in other regions.
### Repairs
- Check both Audience and Issuer field for identifying if a given Token is an AAD Token.
- Return 401 Unauthorized if the authorization process failed.

### Customer workarounds
Set a customized claim provider to overwrite the Issuer field, any value except for "https://sts.windows.net/" is acceptable

```C#
services.AddSignalR()
    .AddAzureSignalR(s => s.ClaimsProvider = (c) =>
    {
        var claims = c.User.Claims;
        return claims.Concat(new Claim[] { new Claim("iss", "") });
    });
```

**Comment by ariveraati** [comment]
This issue took our production environment down for an entire day. I am curious why the status page was not updated to reflect at least a partial degradation of your managed service? What about impact to SLAs?

**Comment by chenkennt** [comment]
We apologize for the downtime this issue caused to your production environment. If you believe your production workload has been affected by this issue with SLA impact, please open a customer support ticket to have it processed based on our promised SLA. 

Regarding Azure status page, a general guideline from Azure (a good article can be found [here](https://azure.microsoft.com/en-us/blog/when-to-use-azure-service-health-versus-the-status-page/)) is it is mainly for outages that all customers and major scenarios are impacted. Since this issue only impacts customers who use AAD, we ended up using [Azure service health](https://aka.ms/ash-statuspage-blog) to inform each customer in the impacted regions. If you go to service health in Azure portal you should be able to see an alert regarding this outage.

**Comment by nazarnku** [comment]
While negotiating, it returns an error of unexpected json, it is happening when client and hub are agree to connect but at that time it gives empty json, I don't know why it happens, any help?

**Comment by vicancy** [comment]
Hi @nazarnku  please open a new issue describing your issue, repro steps and logs from your client and server for us to look into your issue. Thanks!
