### ISSUE TITLE
Unable to pass information from the client to the hub

### ISSUE THREAD

**Issue by yigitgursoy** [Azure/azure-signalr#108]
Context.GetHttpContext() returns the HttpContext in SignalR mode, but returns null in AzureSignalR mode. Therefore I can't read any QueryString or custom Http Header values in the OnConnectedAsync() method of the Hub. I'm using the following code to create the connection.

```csharp
var connection = new HubConnectionBuilder().WithUrl("http://localhost:5000/message?t=TestValue",
                    options => options.Headers = new Dictionary<string, string>
                    {
                        {
                            "X-CustomHeader", "CustomValue"
                        }
                    })
                .Build();
await connection.StartAsync();
```

Is there any way to pass information from the client to the hub using the AzureSignalR service?

**Comment by xscript** [comment]
Yes, the headers are not passed through from client to server. We will need some discussion to decide whether to support it.
A work around is to create a separate hub method and call this method to send information once the client is connected.

**Comment by xscript** [comment]
The fix is ready and on the way to be deployed to production.
A workaround is you can add the room id in a custom claim. We have an option called [ClaimsProvider](https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR/ServiceOptions.cs#L38). The default behavior is we will get `HttpContext.User.Claims` to generate the access token, which will be used to authenticate with Azure SignalR Service.
You can customize the claims by adding your custom claim like below. And in your hub, you can get the custom claim from `Hub.Context.User`.
```csharp
services.AddSignalR()
        .AddAzureSignalR(options =>
        {
            options.ClaimsProvider = context =>
            {
                var claims = context.User.Claims.ToList();
                claims.Add(new Claim("<your-namespace>.room.id", "1"));
                return claims;
            };
        });
```

**Comment by maxiptah** [comment]
Do you have an estimation as to when this fix is going to be deployed?
I'm trying to pass an auth0 token to the hub method. This is normally passed as a bearer token in authorization header. However as stated in this [post](https://stackoverflow.com/questions/15528221/passing-token-through-http-headers-signalr), custom header is not possible because of limitations of JS websocket client which does not allow for it. So I wanted to pass my token as query parameter, but it never reaches my hub. 
Where should I read the query parameters anyway? From Context.Items?

**Comment by xscript** [comment]
I can't give you a concrete time when the deployment is finished. Deployment is not a one-day job. We have to update multiple regions and also thousands of existing instances.
An optimistic estimate is that it will be ready in production at next week (week of 2018/8/27). But it is not guaranteed. I will update here once the deployment is completed.

After the fix is in production, you will be able to access `Hub.Context.GetHttpContext().Request`.

**Comment by xscript** [comment]
Update:
Production deployment has completed. Use [the latest Service SDK](https://www.nuget.org/packages/Microsoft.Azure.SignalR/1.0.0-preview1-10200) and you will be able to access `HttpContext.Request.Headers` and `HttpContext.Request.QueryString`.

**Comment by xscript** [comment]
Close this issue as there is no response over a week.

**Comment by petkoo55** [comment]
Hello xscript,

Was that fixed also within Microsoft.Azure.SignalR.AspNet SDK? Because I am still getting null from Hub.Context.GetHttpContext().

**Comment by xscript** [comment]
> 
> Was that fixed also within Microsoft.Azure.SignalR.AspNet SDK? Because I am still getting null from Hub.Context.GetHttpContext().

@vicancy could you help confirm on this?

**Comment by vicancy** [comment]
> Was that fixed also within Microsoft.Azure.SignalR.AspNet SDK? Because I am still getting null from Hub.Context.GetHttpContext().

No its not, created an issue https://github.com/Azure/azure-signalr/issues/473 to track it.
