### ISSUE TITLE
[Question] How to specify MessagePack settings using the management API

### ISSUE THREAD

**Issue by ModernRonin** [Azure/azure-signalr#1284]
When using the management API - like
```csharp
 var serviceManager = new ServiceManagerBuilder().WithOptions(o =>
                    {
                        o.ConnectionString = signalRConfiguration.ConnectionString;
                    })
                    .Build();
```
how can I tell it which MessagePack settings to use?

I understand that it automatically activates the MessagePack protocol, but I require specific configuration for MessagePack, how can I do that?

Thanks,
MR

**Comment by wanlwanl** [comment]
In Persistent mode, we use [ServiceProtocol](https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR.Protocols/ServiceProtocol.cs) to let server communicate with service.
In Transient mode, actually we send http request to call REST API.
Messagepack is already supported. 
I guess what you need to configure is on your client: https://docs.microsoft.com/en-us/aspnet/core/signalr/messagepackhubprotocol?view=aspnetcore-5.0#configure-messagepack-on-the-client
```C#
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.Extensions.DependencyInjection;

var hubConnection = new HubConnectionBuilder()
                        .WithUrl("/chathub")
                        .AddMessagePackProtocol()
                        .Build();
```

**Comment by ModernRonin** [comment]
Hi & thanks @wanlwanl ,

so, just to make sure I understand you correctly:

if I setup the `serviceManager` with 
```csharp
 var serviceManager = new ServiceManagerBuilder().WithOptions(o =>
                    {
                        o.ConnectionString = signalRConfiguration.ConnectionString;
                    })
                    .Build();
```
and then use it like this
```csharp
await using var context =_serviceManager.CreateHubContextAsync(NotificationConstants.HubName);
await context.Clients.Group(groupName).SendCoreAsync(channel, arguments);
```

and on the client I add my messagepack settings into the `.AddMessagePackProtocol()` call, then it should just work?


```

**Comment by wanlwanl** [comment]
I see, you not only need to add `AddMessagePackProtocol`, but also have custom options on it. We don't support it in Management SDK.

**Comment by ModernRonin** [comment]
Is this something with any likelihood to change in the near future (let's define near as within the next 1-2months) or not?

**Comment by ModernRonin** [comment]
alternatively, if, without doing any special configuration, with the default setup, I send a `byte[]`, will this be sent over the wire in binary format (so the serialized size equals the length of the array) or will it be serialized to JSON (so the size would be many times the length of the array)?

**Comment by wanlwanl** [comment]
No, we don't have a plan to change, since we also have a feature of upstream, when client send mesaage with special hub protocol, the signalr service cannot understand the special protocol. And we have no plan to support uploading it for now.

Thanks,
Wanpeng Li

________________________________

**Comment by wanlwanl** [comment]
Signalr service will only count outbound message (message that is go out of signalr service) for the protocol of client. So you can add message pack protocol to your client to avoid increasing billing (serialized to JSON for your client).
________________________________

**Comment by wanlwanl** [comment]
In default config, the management sdk calls rest api, which will serialize to json, but it will not impact the billing since it is inboind message.
But it can be slower. Suggest to use Persistent mode in WithOptions(...), it will create a websocket to signalr service to.communicate later, and use messagepack protocol inside, it is faster than the default one (transient mode) https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md#transport-type

Thanks,
Wanpeng Li

________________________________

**Comment by ModernRonin** [comment]
thank you, Wanpeng Li, I will look into that!

**Comment by Y-Sindo** [comment]
Now MessagePack is also supported in the persistent mode and you could customize the MessagePack serialization options. Please note that this might break things if you also have SignalR Functions trigger to receive your client invocations because SignalR trigger uses default MessagePack serialization options. You could update your SDK to the latest version and follow [the guide here](https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md#message-pack-serialization) .
