### ISSUE TITLE
Is it possible to use Azure SignalR  Server in a non-webapp .net core project?

### ISSUE THREAD

**Issue by hmrc87** [Azure/azure-signalr#1316]
Is it possible to use Azure SignalR in a non-webapp .net core project like a standard console application? I only managed to get it working using a mvc project where Azure SignalR gets wired in Startup.cs

**Comment by Y-Sindo** [comment]
Please take a look at [Azure SignalR Service Management SDK](https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md). 
And we'll also release a new set of APIs in Management SDK soon, to provide more functions.
Please let us know if this satisfies your need.

**Comment by vicancy** [comment]
What functionalities do you want using a standard console app?

Azure SignalR has a `serverless` mode that your clients connect to the service and you can have the console application sending messages to the connected clients as @Y-Sindo shares above, is that enough for your scenario?

**Comment by wanlwanl** [comment]
add sample here https://github.com/aspnet/AzureSignalR-samples/tree/main/samples/Management for quick start

**Comment by hmrc87** [comment]
Thanks, this helps a lot. One quick question: I am using Azure-SignalR in my Web Startup.project and then in my controllers. I want to use the same Hubcontext in a console application in the same solution. Is this possible?

**Comment by Y-Sindo** [comment]
Yes, these two projects should have no conflicts. Do you have more specific concerns on this?

By the way, we'll release new APIs to build the `ServiceHubContext` directly instead of creating it from `ServiceManager` in a few weeks. The new APIs will support more features such as closing connections, checking if a connection/user/group exists. See [ServiceHubContextBuilder](https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR.Management/ServiceHubContextBuilder.cs),  [ServiceHubContext](https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR.Management/ServiceHubContext.cs). And the transition from old APIs to new APIs should be easy. Just want to provide more information for your decision.
