### ISSUE TITLE
Culture and UI culture are not applied correctly in Blazor application

### ISSUE THREAD

**Issue by GUERCBX** [Azure/azure-signalr#1872]
When using the .NET cookie (.AspNetCore.Culture) to set culture and UI culture of a Blazor application (as described here https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-8.0#dynamically-set-the-server-side-culture-by-user-preference), the culture (i.e., numbers/dates formatting) and the UI culture (i.e., language) are not set correctly after the introduction of the Azure SignalR service. Examples:

Without Azure Signal R (expected behavior):
- When cookie value is "c=en|uic=it", english is used for numbers/dates formatting, while italian is used for texts
- When cookie value is "c=it|uic=en, italian is used for numbers/dates formatting,  while english is used for texts

After the introduction of Azure Signal R (with .AddAzureSignalR())
- When cookie value is "c=en|uic=it", english is used for both numbers/dates formatting and texts
- When cookie value is "c=it|uic=en, italian is used for both numbers/dates formatting and texts

-> it seems that with Azure SignalR, only the "c" part of the cookie is used to set both culture and UI culture of the application.

### Further technical details
- .NET version: 7.0.403
- Azure SignalR SDK version: 1.22.0

**Comment by BrennanConroy** [comment]
It looks like only the culture is grabbed during negotiate https://github.com/Azure/azure-signalr/blob/4609c43f36337101a34a0f668f499b5eb86c30c8/src/Microsoft.Azure.SignalR/HubHost/NegotiateHandler.cs#L82

Then later set on the server connection in https://github.com/Azure/azure-signalr/blob/4609c43f36337101a34a0f668f499b5eb86c30c8/src/Microsoft.Azure.SignalR/ServerConnections/ClientConnectionContext.cs#L282 but since UI culture wasn’t captured it won’t be correct.

cc @vicancy

**Comment by vicancy** [comment]
Should be fixed in the latest 1.24 release
