### ISSUE TITLE
InvalidOperationException while using AzureSignalRService with MultiTenant class in Hub

### ISSUE THREAD

**Issue by himalpatel81** [Azure/azure-signalr#300]
I've created a sample application which uses multi tenancy using Saaskit Multitenancy. and inject the multi tenant class as dependency injection in Hub. 

Project works fine when Azure SignalR Service isn't used. but while using Azure SignalR Service it doesn't work. and gives following error in few seconds after signalR service gets connected. 

signalr.js:1881 Error: Connection disconnected with error 'Error: Server returned an error on close: Connection closed with an error. InvalidOperationException: Unable to resolve service for type 'WiredBrain.MultiTenant.AppTenant' while attempting to activate 'WiredBrain.Hubs.CoffeeHub'.'.

[Git Hub Repro](https://github.com/himalpatel81/AzureSignalRDemo)

You need to replace {AzureServiceEndPointConnectionString} with the Azure SignalR Service EndPoint Connection String in ConfigureServices method of Statup Class.

There is another branch "multitenantwithoutAzureService". and SignalR works fine in there.

**Comment by vicancy** [comment]
I am afraid this third-party package `SaasKit.Multitenancy` to handle multi-tenancy is not supported when using Azure SDK with its current way dealing with DI.

Under the hood, this `SaasKit.Multitenancy` actually registers a HTTP middleware, and when a new HTTPrequest comes in, it registers the object to DI if necessary, according to https://andrewlock.net/loading-tenants-from-the-database-with-saaskit-in-asp-net-core/#configuring-the-services-and-middleware

However when it comes to Azure SDK, there is no new http request invoked. All the connections from client goes to service and then goes into an already-established server-service connection and then directly create the required Hub from DI dynamically. There is nowhere for the middleware of `SaasKit.Multitenancy` to be invoked.

One alternative way is to add singleton AppTenantResolver when ConfigureServices, and resolve the AppTenant inside the Hub. remember to remove the UseMultitenancy line in Configure. Do notice that the Context.GetHttpContext().Request.Host.Value is the ASRS endpoint "sgtest.service.signalr.net" because the client is actually talking to ASRS.

If you want to pass app server url, e.g. localhost:60907, through ASRS to the Hub, you can set the value from client in the URL query string and fetch it from the Hub through: connectionBuilder.WithUrl("/coffeehub?url=localhost:60907")

**Comment by vicancy** [comment]
Closing this as the solution is provided.
