### ISSUE TITLE
SDK cannot detect some clients dropped when ASRS instance crashed.

### ISSUE THREAD

**Issue by vwxyzh** [Azure/azure-signalr#416]
Condition:
* ASRS instance crash.
* The ASRS instance for client connection is different from the instance for server connection.

Problem:
1. These clients will send ping, and app server do not notify offline for these clients.
2. No error will be throw.
3. These clients can be removed when server connection stopped.

**Comment by alexiordan** [comment]
Any updates on this?

**Comment by JialinXin** [comment]
I'm working on this.

**Comment by alexiordan** [comment]
Hi @vicancy  
1. When should I expect this fix to reach production?
2. This is server side only, right? I mean, is there anything should I update (nuget packages etc.)?

**Comment by JialinXin** [comment]
Hi @alexiordan, the fix would be in next SDK release 1.0.12. We did the fix both in Azure SignalR service and server SDK side. ASRS side would be released in 2-3 weeks, and sever SDK release will be after that. Hopefully it would be in a month. 
So when you find 1.0.12 releasing, you need to update to this version of SDK in order to apply the fix. And yes, it's server side no need client changes.
