### ISSUE TITLE
[ASP.NET]Preserve client request information in Hub's Context

### ISSUE THREAD

**Issue by vicancy** [Azure/azure-signalr#473]
User's getting `null` from `Hub.Context.GetHttpContext()`

Dependent on ASP.NET client 2.4.1 https://github.com/SignalR/SignalR/issues/4353

**Comment by petkoo55** [comment]
Thank you Vicancy,

I am using standard SignalR so that I am creating cookies on client side (website) and also via hubConnection.CookieContainer.Add (desktop app)... When you fix it will be these cookies also available on server side? Because currently I tried to use hub.Context.Request to get cookies but there is cross-domain issue.

**Comment by jraristi** [comment]
Are there any news about this issue? Right now we are using the workaround described here https://github.com/Azure/azure-signalr/issues/108

**Comment by vicancy** [comment]
I am afraid not, only `QueryString` and `Headers` will be preserved. @petkoo55

It will be released in next version. @jraristi
