### ISSUE TITLE
Document how to set environment variable for connection string in Linux

### ISSUE THREAD

**Issue by xscript** [Azure/azure-signalr#55]
Right now it is `Azure:SignalR:ConnectionString`, which is not convenient for Linux users. Because `:` is not allowed in environment variable.

**Comment by xscript** [comment]
Answered by https://github.com/MicrosoftDocs/azure-docs/issues/8989
Close this one.

**Comment by johnkors** [comment]
Related.

How about the _value_ of the connectionstring itself, which may include semicolons? I can always build it myself in code, just seems a bit off.

`DefaultEndpointsProtocol=https;AccountName=<some-account>;AccountKey=<key>`

**Comment by davidfowl** [comment]
>How about the value of the connectionstring itself, which may include semicolons? I can always build it myself in code, just seems a bit off.

What do you mean?

**Comment by anurse** [comment]
@johnkors are you talking about an Azure SignalR connection string? The one you cited looks like Azure Storage, not Azure SignalR. Also, generally connection strings are intended to be copied from the portal and used as-is, not constructed manually.

**Comment by johnkors** [comment]
Sorry, this was the only issue I could find with any relevance - not directly related to SignalR.

Yes, this is an Azure Storage connection string. My local dev machine is a Mac using zsh. I think the issue is with my local setup on my mac, and not a general issue. I could not repro using a Linux docker build in a [repro](https://github.com/johnkors/env-repro).

```
var host = new HostBuilder()
            .ConfigureAppConfiguration((hostContext, configApp) =>
            {
                configApp.AddEnvironmentVariables();
            })
        .Build();

var connStr = config.GetValue<string>("ConnStringWithSemiColons");
Console.WriteLine($"The value fetched: '{connStr}'");
```

Local mac env vs docker build output:
<img width="741" alt="Screenshot 2019-07-23 at 11 37 39" src="https://user-images.githubusercontent.com/206726/61701377-56f53980-ad3e-11e9-9a5b-b62b28d3c9a7.png">

On my dev box, I set the env variable in `.zshrc` using `export ConnStringWithSemiColons=ThisIsStuff;OtherStuff;LastlyStuff;KthxBye`. Running locally just outputs the first segment up to the first semicolon.

**Comment by anurse** [comment]
That's because `;` is a statement terminator in zsh, just like in languages like C#. So ZSH stopped parsing at the first `;`. If you quote the string, you should be able to avoid that:

```
export ConnStringWithSemiColons="ThisIsStuff;OtherStuff;LastlyStuff;KthxBye"
```

**Comment by johnkors** [comment]
Neat, thanks!
