### ISSUE TITLE
When reach message limit, service should return 429 instead of 500

### ISSUE THREAD

**Issue by vicancy** [Azure/azure-signalr#635]
This happens to free instances that have 20k/day message limit

**Comment by zackliu** [comment]
If customers hit the message count limit, all the server connections will be terminated. So, client connections will get 500 during app server's negotiate as there're no active server connections.
To identify the root cause, from app server's logs, there should be some critical level logs such as `Service returned handshake error: Maximum message count limit reached: 20000`
Also, for those terminated client connections, there's also a websocket frame such as `{"type":7,"error":"Message count reaches limit."}`

**Comment by vicancy** [comment]
So the behavior is as expected and nothing needs to be changed.
