### ISSUE TITLE
Generating JWT for SignalR Service Rest API

### ISSUE THREAD

**Issue by blawford** [Azure/azure-signalr#666]
I am trying to create a serverless implementation of a Azure SignalR Service I have been a bit lost about how I should approach it.

The main 'broadcasts' will be from a .NET Framework project that will need to call the SignalR Service from C# code. I will also need to broadcast directly from the clients (JavaScript). 

I have created a Azure Function App with a 'negotiate' function which works in terms of getting the clients connected. 

1. To make them able to broadcast messages would I then create a second function? 
2. Same for adding them to a group?

I have read about the SignalR Service REST API, would this be the best way of sending messages from back-end C# code in my web app? From the documentation I am a bit unsure about the best way to consume the API in .NET Framework, is it just a case of sending Http requests or is there a .NET Framework nuget package?

I terms of authenticating with the API, can I use the response of by my Azure Function app negotiation function?

**Comment by vicancy** [comment]
Try the [Management package](https://www.nuget.org/packages/Microsoft.Azure.SignalR.Management), it is .NETStandard 2.0 and it should work for your .NET Framework project. Here is the details on how to use it : https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md

Make sure to use ASP.NET Core SignalR JavaScript client https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.2 because for serverless cases, Azure SignalR only supports the ASP.NET Core SignalR protocol

**Comment by realwanpengli** [comment]
We don't support REST API for ASP.Net.

For ASP.Net **Core**:
Different functions for different purposes. Recommend to use [Azure Functions Bindings for Azure SignalR Service](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.SignalRService). Samples can be found [here](https://github.com/Azure/azure-functions-signalrservice-extension/tree/dev/samples).
