### ISSUE TITLE
Azure SignalR service IP ranges inquiry

### ISSUE THREAD

**Issue by crow-ua** [Azure/azure-signalr#692]
We are developing a solution that integrates with on-premises and need to provide IP ranges of our services to whitelist for IT admins. [Azure IP Ranges and Service Tags – Public Cloud document](https://www.microsoft.com/en-us/download/details.aspx?id=56519) does not list IP ranges for Azure SignalR. Where do we get this information?

**Comment by juniwang** [comment]
Hi @crow-ua , we are sorry that Azure SignalR Service hasn't completed the Service Tag onboarding, that's why it's not included in the public document. The product group is actively working on this. There is no definete timeline(because serveral uncertain dependencies), but we will try our best. There are many customer reqeuests for it.

For now, the IP address for SignalR Service is randomly allocated, it's very difficult to list the IPs or IP range. Apologies again.

**Comment by crow-ua** [comment]
Good to know. We'll list hostname of our Azure SignalR instance for now and hope it will not have big customer impact. 
Let's leave this ticket open until the issue is resolved?

**Comment by juniwang** [comment]
Thanks. Will leave you know once we get it done

**Comment by vicancy** [comment]
It's now supported https://docs.microsoft.com/en-us/azure/azure-signalr/howto-service-tags
