### ISSUE TITLE
Azure App Service and Function App communicating over SignalR

### ISSUE THREAD

**Issue by ThomasVandenbon** [Azure/azure-signalr#713]
I've added Azure SignalR to a web app, with one mapped hub:
`app.UseAzureSignalR(routes =>
{
    routes.MapHub<MyHub>("/MyHub");
});`
In the javascript code of this web app, I connect to this hub through the `HubConnectionBuilder`.
So far so good, I can send messages from this connection and receive them!

Next, I've added a SignalR binding to an Azure Function:
`[SignalR(
    ConnectionStringSetting = "Azure:SignalR:ConnectionString",
    HubName = "MyHub")] IAsyncCollector<SignalRMessage> signalRMessages,`

However, when I try to push messages using this SignalR-binding:
`await signalRMessages.AddAsync(new SignalRMessage { Target = "Update" });`
The connection build with the `HubConnectionBuilder` isn't receiving any messages from this Azure Function at all.

Note:

- I'm not seeing any errors at all.
- My service mode is set to "Default"

My questions:

- Am I trying to do something that is impossible: can an Azure Function not communicate with a web app in this fashion? And if so, what is the alternative?
- How do I diagnose a problem like this? I've not found any place in the Azure Portal where I could look into the sent messages or active hubs.
- Why does the "Message Count (total)" in the Azure Portal (on the Overview page) always show 0 messages, even when my HubConnectionBuilder is receiving messages?
- What does service mode "Default" really mean? I've not been able to find a good explanation anywhere.

**Comment by JialinXin** [comment]
@ThomasVandenbon This should be able to work. 

> * How do I diagnose a problem like this? I've not found any place in the Azure Portal where I could look into the sent messages or active hubs.

You can open browser DevTools F12 and check client side messages under Network tab like below.
![image](https://user-images.githubusercontent.com/15338714/67915105-0313af80-fbcd-11e9-84fb-6e61bbaa9927.png)

> * Why does the "Message Count (total)" in the Azure Portal (on the Overview page) always show 0 messages, even when my HubConnectionBuilder is receiving messages?

We're counting message count by MessageSize/2KB, it shows 0 may be caused by the size is too small. 

> * What does service mode "Default" really mean? I've not been able to find a good explanation anywhere.

* `Default` means you **must** have a server to host server connection. And your clients will always route to a server connection.
* `Serverless` means your client doesn't need server connection and it works for Azure Function and RestAPI scenarios only.
* `Classic` means you can use mixed, that if there's a server, your client will be route to a server connection, and if not, it will auto fallback to `Serverless` mode.

To make it work smoothly, beside using same hub, you also need to uniform the client side listening message in same formats. Checking the snapshot above, you may notice the 5th message arguments is different from other broadcastMessages, which is coming from my Azure Function.

**Comment by janlesage-allphi** [comment]
@JialinXin I encountered this issue with @ThomasVandenbon and we tried several scenarios:

Scenario 1:
We make use of UseAzureSignalR with defined routes and MapHub. Eg app.UseAzureSignalR(routes => { routes.MapHub<MyHub>("/MyHub"); });
This is possible with SignalR service in Default and exposes the ".../negotiate" automagically
In the docs there is only mentioned that in order for Azure Functions to work with Azure SignalR Service you *must* set the service mode to Serverless. This makes it incompatible with the routes.MapHub scenario

Scenario 2:
We make use of UseAzureSignalR() nothing defined. Inside the Management sample we used the NegotiateController and tested our app + sample sender + sample client. We can broadcast and receive on both the app and sample client/sender. Here we had set the mode to the apparently required Serverless mode, since we need functions to interact with the same SignalR Service.

In the docs we found examples for dotnet core which use the MapHub method, and examples for the functions, however it seems to us like these are incompatible worlds, since functions need serverless mode and maphub is not compatible with serverless mode.

Either way, we are unable to get any function to send properly with an output binding to SignalR

**Comment by JialinXin** [comment]
@janlesage-allphi If you have server side web app, you should use `Default` or `Classic` mode. The document means if you work on ASRS with Azure Function only, then you should enable `Serverless` mode or `Classic` mode. Actually under Azure Function, you still need to target a hub. 
Azure Function Example. https://github.com/Azure/azure-functions-signalrservice-extension/blob/dev/samples/simple-chat/csharp/FunctionApp/Functions.cs#L28
``` cs
[FunctionName("negotiate")]
        public static SignalRConnectionInfo GetSignalRInfo(
            [HttpTrigger(AuthorizationLevel.Anonymous)] HttpRequest req,
            [SignalRConnectionInfo(HubName = "simplechat", UserId = "{headers.x-ms-signalr-userid}")] SignalRConnectionInfo connectionInfo)
        {
            return connectionInfo;
        }
```

Have you checked client traces about messages being broadcast?

**Comment by sffamily** [comment]
Hi @ThomasVandenbon , @janlesage-allphi , I cannot find your contact so ping you guys here. I'm the Product Manager of Azure SignalR Service, and we have a new internal preview for supporting raw WebSocket in serverless scenarios, with more complete Azure Functions integration scenario, thinking you might be interested to try it out and offer us some feedback. If you are interested please ping me at zhshang at microsoft dot com.  Thanks. -Zhidi

**Comment by JamesHyot** [comment]
Hi all,

I'm having the same issue. I have an Azure App Service running hub logic on ASP.NET Core SignalR, using Azure SignalR Service for scaling. The SignalR service is on **Default** mode as I have a server for it to run on. Connecting to my AppService hub from my Javascript client through Azure SignalR Service works fine. Sending messages to this hub and receiving messages in response works fine.

However I sometimes need to send messages to users/groups based on ServiceBus messages I receive. I created an Azure Function App that retrieves the messages and uses a SignalR output binding to connect to Azure SignalR Service and send messages through it. Client-side, I'm not able to receive anything, and I've tried sending messages with different targets, different arguments, I've sent them to groups, to connections, to users and even to everybody, to no avail.
I then tried to use the REST Api in case I misused the Function App binding. Same thing happened there, I cannot receive anything.

My guess is that the REST Api and Funtion App output binding only work with Serverless mode, which is a shame...
Am I forced to call a Controller endpoint on my App Service from my Function App to tell the App Service which messages it needs to broadcast using an injected IHubContext ?

**Comment by JialinXin** [comment]
@JamesHyot You'd switch to **Classic** mode if you're using them mixed.

**Comment by AdamDiament** [comment]
> @JamesHyot You'd switch to **Classic** mode if you're using them mixed.

I am in this scenario but I don't want to use "classic" mode - from the azure docs it says it is a really bad idea.

```
Classic mode is mainly for backward compatibility for those applications created before there is default and serverless mode. It's strongly recommended to not use this mode anymore. For new applications, please choose default or serverless based on your scenario. For existing applications, it's also recommended to review your use cases and choose a proper service mode.
```

> Am I forced to call a Controller endpoint on my App Service from my Function App to tell the App Service which messages it needs to broadcast using an injected IHubContext ?

I had this idea too, it seems like overkill but I can't think of an alternative that doesn't involve hosting two azure signal r service apps.

**Comment by raffi1965** [comment]
@AdamDiament I am in this scenario too and use Classic mode.
But before run in production I would like to make sure that classic mode is LTS
Have you get another idea?

**Comment by JialinXin** [comment]
@AdamDiament, @raffi1965 `Classic` mode is supported. And we keep this cause some customer do need this mixed mode. The service mode is per SignalR resource, and when using `Classic` mode the risk is if the servers are offline, and service will fallback to `Serverless` mode, then new clients would lose control by the servers. 

The cost for a 2 SignalR unit 1 is same as 1 SignalR unit 2. It's suggested to split it from resource level if the 2 mode are targeting different hubs for a consistent behavior you're expected. Otherwise, you need to be aware of the potential risk of the `Classic` mode when using this.
