### ISSUE TITLE
 Microsoft.Azure.SignalR.Protocol MessagePack V2 breaking change

### ISSUE THREAD

**Issue by marcodemagalhaes** [Azure/azure-signalr#799]
Hi

When I upgraded messagepack to v2 the Microsoft.Azure.SignalR.Protocols package started to get error because it implements v1

There are plans to migrate to messagepack v2?

Thanks!

**Comment by vicancy** [comment]
As https://github.com/dotnet/aspnetcore/pull/18133#issuecomment-570937428, we will follow the same practice to build MessagePack from source to prevent such issues in the future.

**Comment by tebeco** [comment]
hello @vicancy

i've just tried to attempt the migration too here :
https://github.com/tebeco/azure-signalr/tree/msgpack-v2

* what should be the base branch ? since this SDK has a different lifetime than SignalR
* am i suppose to target `netstandard2.0` only ? or should i cross target `netcoreapp3.1` since aspnetcore3.x is only `netcoreapp3.x`
  also `netcoreapp3.x` might have extension method for `Memory/Span/...` that cannot exist in `netstandard` since these enhancement requires has been made in both runtime and GC as i understand it

current branch state : 
* build ok
* ~ 100+ test KO
* pretty sure i did not migrate the `WriteBytes()` properly (the 2 block with `// REVIEW`) i'm trying time see if i can do a `Span/Slice` and why the Loop+`TryGet`
* some tests seems to fails because of a connection Handshake failure, i'm not sure if the `ConnectionString` i use is supposed to target `Default|Classic|Serverless` or if i can inject multiple connection string

**Comment by tebeco** [comment]
I think that thank to this commit :

I'm down to this :
![image](https://user-images.githubusercontent.com/2266487/72648761-2ce2a400-397c-11ea-84bf-271c0fe3df30.png)

All error here are present because this respository explicitly depends on `MessagePackHubProtocol` from `Microsoft.AspNetCore.SignalR.Protocols.MessagePack` (v3.0.0 <== this might be a good idea to update it, at least to 3.1.0 for LTS), which is `MessagePack 1.7.x`

34 Tests are KO are from `ServiceLifetimeManagerFacts` :
```
    System.TypeInitializationException : The type initializer for 'Microsoft.Azure.SignalR.Tests.ServiceLifetimeManagerFacts' threw an exception.
    ---- System.TypeInitializationException : The type initializer for 'SignalRResolver' threw an exception.
    -------- System.MissingFieldException : Field not found: 'MessagePack.Resolvers.DynamicEnumAsStringResolver.Instance'.
  Stack Trace: 
....
    MessagePackHubProtocol.CreateDefaultFormatterResolvers()
    MessagePackHubProtocolOptions.ctor()
    MessagePackHubProtocol.ctor() <============================ THIS
....
```

The 2 other errors are `UseAzureSignalRWithConnectionStringNotSpecified` / `UseAzureSignalRWithInvalidConnectionString`
And the Exception is the same (the `StackTrace` show another constructor, but end up the same way)

**Comment by tebeco** [comment]
@marcodemagalhaes 
I'm a bit ahead of schedule as it is not "reviewed / merged / released"
But to be clear on the PR, as it look for now, it only "removes" the `Transitive` dependency from `Azure SignalR SDK` on `MessagePack`.
This mean that if you ever use a `SignalR Hub` + `MessagePackHubProtocol`, you will be hit by https://github.com/dotnet/aspnetcore/issues/18692
https://github.com/dotnet/aspnetcore/issues/18692#issuecomment-581869587

So depending on your use of SignalR it self, and the protocol you are using, you might be stuck until `AspNetCore 5.x`.

If you cannot wait until then, and can add complexity to your project, you might be able to fork the actual implementation of the `MessagePackHubProtocol` that has been merged in `dotnet/aspnetcore` on `master` branch
Please check that this is not in violation of any `LICENSE` and then update your `LICENSE`/`3rPartNotice`... to point to the `dotnet/aspnetcore` one ... i think ... **please ask someone more familiar than me on that**

**Comment by vicancy** [comment]
With generous help offered by @tebeco, [v1.4.0](https://github.com/Azure/azure-signalr/releases/tag/v1.4.0) removes the dependency.
