### ISSUE TITLE
Upgrade Auto-generated token from HS256

### ISSUE THREAD

**Issue by VuNhat** [Azure/azure-signalr#834]
Hi guys, currently we are building a public chatbot that is using Azure Signalr Service. 
We observed that the auto-generated token to azure signalr service is using HS256, which result in a failed pen-test from the client.
I'm wondering if there is any guidance to customize the JWT for negotiation step, using stronger algo. Please advise, thank you

**Comment by vicancy** [comment]
Currently, it is not customizable. If `HS256` is weak, which one would you recommend? Shall we directly update the `SecurityAlgorithm` to make it stronger instead of making it customizable? https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR.Common/Utilities/AuthenticationHelper.cs#L75

**Comment by VuNhat** [comment]
hi @vi
I think anything stronger than RS256 should be fine, no need to be customizable. But my concern is, as we are sending this token in the url and not header, will a longer token failed to send?

**Comment by vicancy** [comment]
How about `HS512`? Yes, that will make the URL longer, for HTTP/1.1, or C# clients, the max URI length is 12K, that sounds enough if you don't have too many claims passing to the service.

**Comment by VuNhat** [comment]
Yes that should be good enough. Thank!

**Comment by vicancy** [comment]
Thanks for the confirmation, we will provide an option to choose between `HS256` and `HS512` then.
