### ISSUE TITLE
SignalR ASP.NET with Azure SignalR Service doesn't automatically reconnect

### ISSUE THREAD

**Issue by ajbeaven** [Azure/azure-signalr#839]
When I self host SignalR and simulate connection issues, on the client, `$.connection.hub.reconnecting` is fired, indicating that SignalR is attempting to reconnect. When I move to using Azure SignalR Service, the reconnecting event is no longer fired and the connection is disconnected immediately.

[The post](https://devblogs.microsoft.com/aspnet/azure-signalr-service-now-supports-asp-net/) that announced Azure SignalR Service support for ASP.NET noted that automatic reconnects are not supported. Is this still the case now that SignalR 3.0 supports automatic reconnects?

Presumably automatic reconnecting handles sending non-received messages to clients that are able to reconnect? If that's the case, this functionality is pretty important and is not handled by the [current suggestion](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/handling-connection-lifetime-events#how-to-continuously-reconnect) of starting a new connection when a client disconnects (since they'd be seen as a new client):

```
$.connection.hub.disconnected(function() {
   setTimeout(function() {
       $.connection.hub.start();
   }, 5000); // Restart connection after 5 seconds.
});
```

Any timeline on when automatic reconnecting will come to Azure SignalR Service for ASP.NET if at all?

**Comment by davidfowl** [comment]
Whatever is supported I’m today is what will be supported in the service. It should reconnect for transient client failures, but if the application goes down or the machine where the client connection goes down then it won’t reconnect.

Are you saying it never tries to reconnect? How are you simulating connection failures?

**Comment by vicancy** [comment]
The “reconnecting event" is fired when the connection drops. There is one case when "reconnecting" is not fired when the Azure SignalR Service proactively closes the connection due to, for example, app server restarts and it tells Azure SignalR to close all the clients connected to it. For this case, there will be a message similar to `"E":{"error message"}` inside the WebSocket frame, could you check if that is the case? 

![image](https://user-images.githubusercontent.com/668244/76050217-a91f5e00-5fa1-11ea-8b46-61d2f533e330.png)



If that is not the case, could you enable client-side trace following https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing#enabling-tracing-in-the-javascript-client? That can help diagnose why the "disconnect" decision is made.

**Comment by ajbeaven** [comment]
Thanks for the comments everyone.

> if the application goes down or the machine where the client connection goes down then it won’t reconnect.

> There is one case when "reconnecting" is not fired when the Azure SignalR Service proactively closes the connection due to, for example, app server restarts and it tells Azure SignalR to close all the clients connected to it.

I think these explain what I'm experiencing. I'm simulating 'connection issues' by restarting IIS. When self-hosting SignalR (even with a Service Bus backplane) clients tried to reconnect. When I switched to using the SignalR Service, this behaviour changed so I assumed that reconnection functionality wasn't implemented in SignalR ASP.NET yet.

If this is the only time that all clients are disconnected, I'm fine with this. Any tricks you can recommend to better simulate client connection issues when running locally so I can verify myself?

**Comment by vicancy** [comment]
For client side, how about Chrome's Network Throttling feature https://css-tricks.com/throttling-the-network/

**Comment by davidfowl** [comment]
Unfortunately that doesn't work for websockets 😢

**Comment by ajbeaven** [comment]
Yeah exactly. [The bug](https://bugs.chromium.org/p/chromium/issues/detail?id=423246) is tracked here if it's of interest.

I should ask - are there any plans or would it ever be feasible, to have clients reconnect in the event where the app server restarts? It has been good in the past to be able to deploy changes to the site (it's a 1-on-1 chatting app) and have clients reconnect when it comes back up, so that behaviour is preferable despite not being a deal breaker.

**Comment by davidfowl** [comment]
its about setting the right expectations. The service will never behave exactly like self hosted signalr, it’s not a roadmap thing, it’s intentionally designed that way to improve reliability of the overall system. 

There are a couple of reasons to want reconnect:
1. you want to handle transient client failures 
2. you don’t want to write reconnect logic 
3. you want to persevere missed messages while disconnected.

We currently support 1. in the service.
The second is within a given threshold. The client does not indefinitely try to reconnect. After the threshold it will stop (with on premise and the service). You can think of this as the grace period where reconnection is transparent. TL;DR you still need to write the logic to reconnect the connection once the threshold expires. 

3. Is where the service and signalr hosted differ. We can reconnect if the server goes down but we cannot preserve the state as the connection is tied to the instance where that connection lives. Today we close the connection instead of reconnecting in this case.

Does that make sense?

**Comment by ajbeaven** [comment]
Thanks for that. I really appreciate the candid response and the additional detail you've provided.

Could you kindly please provide some clarification on point 3? If a client is having transient issues, will they receive messages sent to them while the connection is down if they are eventually reconnected?

**Comment by davidfowl** [comment]
> Could you kindly please provide some clarification on point 3? If a client is having transient issues, will they receive messages sent to them while the connection is down if they are eventually reconnected?

Yes. With the service, assuming reconnect succeeding means messages won’t be missed in that time period. Otherwise we drop the connection.

The story is complicated for hosted signalr as it can reconnect even if the server disappears but you can also miss messages if the server you connected to doesn’t have the appropriate connection state (because of a transient server side issue).
