### ISSUE TITLE
Random failures invoking hub methods from .NET Core SignalR client

### ISSUE THREAD

**Issue by sjbthfc2** [Azure/azure-signalr#906]
Hi,

I am using the .NET Core SignalR client (v3.1.4) with Azure SignalR services from an Orleans grain which itself is hosted in an ASP.NET Core 3.1 Web API app. The grain tries to use InvokeAsync to execute a method on the hub to send messages to clients. Sometimes it works, and other times it fails with:

Failed to invoke 'BroadcastMessage' due to an error on the server. HubException: Method does not exist.

My host code has Azure SignalR added through the services.Add methods and I have the Hub map correctly as an endpoint.

My client code looks like:

```
        private HubConnection _connection;

        public async Task Connect(string hubUrl)
        {
            _connection = new HubConnectionBuilder()
                .WithUrl(hubUrl)
                .Build();
            _connection.Closed += async (error) =>
            {
                await Task.Delay(new Random().Next(0, 5) * 1000);
                await _connection.StartAsync();
            };
            await _connection.StartAsync();            
        }
        public async Task Invoke(string userId, string serverMethod, SystemState message)
        {
            await _connection.InvokeAsync("BroadcastMessage", "User1", "Hello from Orleans");
        }
```
And the Hub has the following method:
```
    public class SystemsHub : Hub
    {
        public void BroadcastMessage(string name, string message)
        {
            Clients.All.SendAsync("broadcastMessage", name, message);
        }
```
Is it possible to do this from inside an Orleans grain? Is there a reason why this would randomly find the Hub method and other times fail to do so?

Thank you for any help you can give.

**Comment by vicancy** [comment]
> HubException: Method does not exist.

The most possibility is that you have multiple different (or different versions of) applications with the same `ApplicationName` connected to the **same** Azure SignalR endpoint. Azure SignalR considers connected app server with the same `ApplicationName` and the same `Hub` as multiple instances of the same app and it randomly picks one to route the client traffic to. That's why it randomly fails because the client is randomly routed to a `Hub` with no such method.

The easiest way to work around the issue is to give the app another `ApplicationName` when configuring `ServiceOptions` https://github.com/Azure/azure-signalr/blob/dev/docs/use-signalr-service.md#applicationname.

But I would suggest finding out this other different (or different version of) application in case it might lead to some potential issues in the future.

**Comment by sjbthfc2** [comment]
Thank you so much for your help.

I did indeed have two Orleans silos running on different ports and I stopped one thinking Azure SignalR would no longer use it. I have added an application name and now the Hub method gets called consistently every time. The problem now is that my client, a Blazor WASM app never gets called from the server. Do I need to specify something more in the client connection? My Hub config looks like:

```
app.UseEndpoints(endpoints =>
{
          endpoints.MapControllers();
          endpoints.MapHub<SystemsHub>("/systemsHub");
});

services.AddSignalR()
         .AddAzureSignalR(options =>
         {
                 options.ConnectionString = <SignalR connection string>";
                 options.ApplicationName = "OrleansPoc";
          });
```

And my client connection code in a Blazor component is:

```
        _hubConnection = new HubConnectionBuilder()
            .WithUrl(NavigationManager.ToAbsoluteUri("/systemsHub"))            
            .Build();

        _hubConnection.On<string, string>("broadcastMessage", (user, message) =>
        {
            var encodedMsg = $"{user}: {message}";
            _messages.Add(encodedMsg);
            StateHasChanged();
        });
```

**Comment by vicancy** [comment]
Blazor is natively supported by the latest Azure SDK and there is no additional config required for the client side.
