### ISSUE TITLE
Have ApplicationName rules changed recently?

### ISSUE THREAD

**Issue by klioqc** [Azure/azure-signalr#914]
Looks like ApplicationName we specify on Azure SignalR connection creation on the server side, stopped working recently, if it contains "-" sign. 
Worst thing is that there is nothing I could find in the log, at least for ASP.NET version of the library (not Core). It just returns 400, when trying to connect to ASRS. I had to debug the library to find the URL it calls and see the error in browser then.

Are there any other changing around it? like maxmin length, other forbidden characters, etc..

**Comment by JialinXin** [comment]
Hi @klioqc, thanks for contacting us and sorry that we have a regression bug for AspNet users, and the fix is deploying now, region by region. We've applied the hotfix to a few affected users right after we notice that but may missed yours. It may take some time to roll out to you resource. So would you tell us which region your resource is in? We can help fix that right now.

**Comment by klioqc** [comment]
oh, so this is just temporarily? Ok, then. 
I am still developing so I am using free tier in canadaeast region.
thank you

**Comment by vicancy** [comment]
Should be fixed.
