### ISSUE TITLE
SignalR Redundancy

### ISSUE THREAD

**Issue by samsta1128** [Azure/azure-signalr#972]
Using the latest version of 1.5.0 (Microsoft.Azure.SignalR.Management)

Trying to setup a primary and secondary connection for redundancy following this guideline: 
https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-concept-disaster-recovery

Service manager builder as outlined below doesn't allow a connection string endpoint type (primary or secondary) and doesn't allow you to create endpoints and add them.

var myServiceManager = new ServiceManagerBuilder().WithOptions(option =>
            {
                option.ConnectionString = _configuration["Azure:SignalR:ConnectionString"];
                option.ServiceTransportType = ServiceTransportType.Persistent;
            }).Build();

_mySignalRHubContext = myServiceManager.CreateHubContextAsync("hub").GetAwaiter().GetResult();

Is it possible to do this with this package?

**Comment by wanlwanl** [comment]
`IServiceManager` isn't designed for used as server. It only helps to send message. Maybe add a new class `IServiceManagerContainer` to handle multiple SignalR service instances is a good idea, which include the options to switch endpoints due to some custom conditions. What do you think? @JialinXin @vicancy 

To workaround, you can use the new API [IsServiceHealthy](https://github.com/Azure/azure-signalr/blob/master/src/Microsoft.Azure.SignalR.Management/IServiceManager.cs#L49) to check whether the SignalR service is healthy. You can create multiple `IServiceManager`s to handle multiple SignalR service instances. And switch among instances when one is unavaible.

**Comment by vicancy** [comment]
Please feel free to reopen it if you still have any concerns about it.
